Added documentation for the public paginated API
iottly/iottly.github.io pull request #9
Opened 2020-09-25 16:53 UTC by SaiT2

Added public paginated  api

2020-09-28 13:09 UTC, lupodellasleppa requested changes
`- **to**:  the UUID of the device that receive the message`

Should actually be: `- **to**: the ID of the project where the device is registered`

Other than that, looks good to me! :shipit:

2020-11-09 10:14 UTC, lupodellasleppa requested changes
Also the API endpoint is not correct.

```
curl -H 'Authentication: bearer <API KEY>' https://api.cloud.iottly.com/v1.0/project/<project id>/messages/<device id>
```

should be:

```
curl -H 'Authentication: bearer <API KEY>' https://api.cloud.iottly.com/v1.0/project/<project id>/device/<device id>/messages/paginated
```

2020-11-09 10:25 UTC, lupodellasleppa commented
> Also the API endpoint is not correct.
> 
> ```
> curl -H 'Authentication: bearer <API KEY>' https://api.cloud.iottly.com/v1.0/project/<project id>/messages/<device id>
> ```
> 
> should be:
> 
> ```
> curl -H 'Authentication: bearer <API KEY>' https://api.cloud.iottly.com/v1.0/project/<project id>/device/<device id>/messages/paginated
> ```

dismiss this, my fault

2020-11-09 10:26 UTC, lupodellasleppa approved these changes

2020-11-09 10:28 UTC, Oscar-Campo approved these changes

2020-11-09 10:29 UTC, merged